language: node_js
node_js: 8.9.1
before_install: yarn global add greenkeeper-lockfile@1 yalc
install: yarn --check-files
before_script: greenkeeper-lockfile-update && greenkeeper-lockfile-upload
sudo: false
cache:
  yarn: true
  directories:
  - node_modules
  - ".downstream_cache"
